name: Lifesteal
main: me.Bamle.lifesteal.Lifesteal
version: 1.0
api-version: '1.21'
commands:
  lifesteal:
    description: Main command for Lifesteal plugin
    usage: /lifesteal <reload>
    permission: lifesteal.reload
